#!/usr/bin/env python3
"""
PyCUDA Compiler - Extended Features Examples

Примеры использования расширенных возможностей:
- Рекурсия
- Списки (List)
- Словари (Dict)
- Множества (Set)
- Строки
"""

import sys
sys.path.insert(0, '/home/claude/pycuda_compiler')

from extended_features import (
    StringSupport, DictSupport, ListSupport,
    SetSupport, TupleSupport, OptionalSupport,
    RecursionSupport
)


def demo_recursion():
    """Демонстрация рекурсии."""
    print("=" * 60)
    print("RECURSION SUPPORT")
    print("=" * 60)
    print("""
Python:
    def factorial(n: int32) -> int32:
        if n <= 1:
            return 1
        return n * factorial(n - 1)

Generated CUDA:
""")
    print(RecursionSupport.generate_recursive_function_example())


def demo_lists():
    """Демонстрация списков."""
    print("=" * 60)
    print("LIST SUPPORT (Dynamic Arrays)")
    print("=" * 60)
    print("""
Python:
    result: List[float32] = []
    for x in data:
        if x > 0:
            result.append(x)

Generated CUDA:
""")
    print(ListSupport.generate_list_type('FloatList', 'float', 1024))


def demo_dicts():
    """Демонстрация словарей."""
    print("=" * 60)
    print("DICTIONARY SUPPORT (Hash Table)")
    print("=" * 60)
    print("""
Python:
    counts: Dict[int32, int32] = {}
    for x in data:
        if x in counts:
            counts[x] += 1
        else:
            counts[x] = 1

Generated CUDA:
""")
    print(DictSupport.generate_dict_helpers('IntDict', 'int', 'int', 256))


def demo_sets():
    """Демонстрация множеств."""
    print("=" * 60)
    print("SET SUPPORT")
    print("=" * 60)
    print("""
Python:
    unique: Set[int32] = set()
    for x in data:
        unique.add(x)

Generated CUDA:
""")
    print(SetSupport.generate_set_type('IntSet', 'int', 256))


def demo_strings():
    """Демонстрация строк."""
    print("=" * 60)
    print("STRING SUPPORT")
    print("=" * 60)
    print("""
Python:
    s = "hello"
    length = len(s)
    s2 = s + " world"

Generated CUDA helpers:
""")
    print(StringSupport.generate_string_helpers())


def demo_tuples():
    """Демонстрация кортежей."""
    print("=" * 60)
    print("TUPLE SUPPORT")
    print("=" * 60)
    print("""
Python:
    point: Tuple[float32, float32, float32] = (1.0, 2.0, 3.0)
    x, y, z = point

Generated CUDA:
""")
    print(TupleSupport.generate_tuple_type('Float3', ['float', 'float', 'float']))


def demo_optional():
    """Демонстрация Optional."""
    print("=" * 60)
    print("OPTIONAL SUPPORT")
    print("=" * 60)
    print("""
Python:
    def find(arr, target) -> Optional[int32]:
        for i in range(len(arr)):
            if arr[i] == target:
                return Some(i)
        return None

Generated CUDA:
""")
    print(OptionalSupport.generate_optional_type('OptionalInt', 'int'))


def demo_full_example():
    """Полный пример со всеми возможностями."""
    print("=" * 60)
    print("FULL EXAMPLE: Histogram with Dict")
    print("=" * 60)
    
    cuda_code = '''
// Generated by PyCUDA Compiler (Extended Features)
#include <cuda_runtime.h>
#include <math.h>

// ============ Dictionary Type ============
''' + DictSupport.generate_dict_helpers('Histogram', 'int', 'int', 1024) + '''

// ============ Recursive Functions ============
__device__ int gcd(int a, int b) {
    if (b == 0) return a;
    return gcd(b, a % b);
}

// ============ Kernel ============
__global__ void compute_histogram(
    int* data, int data_size,
    Histogram* hist
) {
    int tid = blockIdx.x * blockDim.x + threadIdx.x;
    
    // Initialize histogram (only first thread)
    if (tid == 0) {
        Histogram_init(hist);
    }
    __syncthreads();
    
    // Each thread processes elements with grid-stride loop
    for (int i = tid; i < data_size; i += blockDim.x * gridDim.x) {
        int val = data[i];
        
        // Atomic increment (simplified - real impl needs atomics)
        int count;
        if (Histogram_get(hist, val, &count)) {
            Histogram_set(hist, val, count + 1);
        } else {
            Histogram_set(hist, val, 1);
        }
    }
}

// ============ Another Example: Filter with List ============
''' + ListSupport.generate_list_type('ResultList', 'float', 4096) + '''

__global__ void filter_positive(
    float* data, int data_size,
    ResultList* result
) {
    int tid = blockIdx.x * blockDim.x + threadIdx.x;
    
    if (tid == 0) {
        ResultList_init(result);
    }
    __syncthreads();
    
    for (int i = tid; i < data_size; i += blockDim.x * gridDim.x) {
        if (data[i] > 0.0f) {
            ResultList_append(result, data[i]);
        }
    }
}
'''
    
    print(cuda_code)


def main():
    """Запуск всех демонстраций."""
    demos = [
        demo_recursion,
        demo_lists,
        demo_dicts,
        demo_sets,
        demo_strings,
        demo_tuples,
        demo_optional,
        demo_full_example,
    ]
    
    for demo in demos:
        demo()
        print("\n")


if __name__ == '__main__':
    main()
