// Generated by PyCUDA Compiler

// Thread indexing helpers
#define THREAD_ID (blockIdx.x * blockDim.x + threadIdx.x)
#define GRID_STRIDE (blockDim.x * gridDim.x)

extern "C" __global__ void square_root_kernel(float* data, int _size_data, float* result, int _size_result) {
    int i;
    for (int i = THREAD_ID; i < _size_data; i += GRID_STRIDE) {
        result[i] = sqrtf(data[i]);
    }
}
